webtalk_init -webtalk_dir C:/Users/Isuru Gunarathne/OneDrive - University of Moratuwa/VIVADO LABS/Lab 9 - 10/Nano Processor/Nano Processor.sim/sim_nanoProcessor/behav/xsim/xsim.dir/TB_nanoProcessor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jul 13 08:10:18 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0879ccaa-7cad-43ae-a5e2-1fea5b496f0e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "859f874d42154cf0a758898fcba34ea8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "29" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5500U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "23" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "73 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "6 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "79" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "51" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "67116_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3194935862 -regid "" -xml C:/Users/Isuru Gunarathne/OneDrive - University of Moratuwa/VIVADO LABS/Lab 9 - 10/Nano Processor/Nano Processor.sim/sim_nanoProcessor/behav/xsim/xsim.dir/TB_nanoProcessor_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Isuru Gunarathne/OneDrive - University of Moratuwa/VIVADO LABS/Lab 9 - 10/Nano Processor/Nano Processor.sim/sim_nanoProcessor/behav/xsim/xsim.dir/TB_nanoProcessor_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Isuru Gunarathne/OneDrive - University of Moratuwa/VIVADO LABS/Lab 9 - 10/Nano Processor/Nano Processor.sim/sim_nanoProcessor/behav/xsim/xsim.dir/TB_nanoProcessor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
